### ISSUE TITLE
等我禮拜六日有空來研究一下JavaScript大師的code

### ISSUE THREAD

**Issue by ghost** [teddy1565/DeskGame0001#1]
嗨嗨，我是郭翔宇。已經幫你的專案按星星了。

**Comment by teddy1565** [comment]
XD沒什麼技術含量就只是前端用bootstrap+ajax
做個簡單的表單回應 以及資料庫寫入寫出的動作
幫學長解決一些簡單的問題

HsiangYu3 <notifications@github.com> 於 2020年9月3日 週四 下午2:33寫道：

**Comment by ghost** [comment]
> 嗨嗨，我是郭翔宇。已經幫你的專案按星星了。
